version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: chamados-postgres
    environment:
      POSTGRES_DB: chamadospt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chamados-network

  # Backend SpringBoot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chamados-backend
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/chamadospt
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - chamados-network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chamados-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chamados-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  chamados-network:
    driver: bridge