spring:
  application:
    name: chamados-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chamadospt}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  web:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:3001"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

server:
  port: ${PORT:8080}

logging:
  level:
    com.petrobras.chamados: DEBUG
    org.springframework.web: DEBUG